server:
  port: 8080
  
spring:
  application:
    name: cep-service
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cep-service
    username: postgres
    password: P123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: core
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      